#!/usr/bin/env python3
"""Generate multi-level navigable ecosystem map with links.

Level 1: index.md — compact plugin list with links
Level 2: {plugin}/index.md — plugin detail with links to skills/agents
Level 3: {plugin}/skills/{name}.md — individual item detail
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.scan_plugins import scan_plugin
from lib.write_plugin_map import write_plugin_map


def main() -> None:
    """Orchestrate multi-level map generation."""
    script_dir = Path(__file__).resolve().parent
    plugins_dir = (
        Path(sys.argv[1]) if len(sys.argv) > 1 else script_dir.parent.parent
    )
    output_dir = (
        Path(sys.argv[2]) if len(sys.argv) > 2  # noqa: PLR2004
        else Path(".cartographer")
    )

    plugins_dir = plugins_dir.resolve()
    if not plugins_dir.is_dir():
        sys.stderr.write(f"Error: plugins dir not found: {plugins_dir}\n")
        sys.exit(1)

    output_dir.mkdir(parents=True, exist_ok=True)

    plugin_dirs = sorted(
        d for d in plugins_dir.iterdir()
        if d.is_dir() and not d.name.startswith(("_", "."))
    )

    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M")
    index_lines = [
        f"# Ecosystem Map ({len(plugin_dirs)} plugins)\n",
        f"> Auto-generated by cartographer — {now}\n",
    ]

    for plugin_path in plugin_dirs:
        version, pkg_name = _read_plugin_meta(plugin_path)
        display = pkg_name or plugin_path.name
        items = scan_plugin(str(plugin_path))
        agents = [n for t, n, _ in items if t == "agent"]
        agents_str = ", ".join(agents) if agents else "(no agents)"
        ver = f" (v{version})" if version else ""
        index_lines.append(
            f"- [{display}](./{display}/index.md){ver} → {agents_str}",
        )
        write_plugin_map(output_dir, display, version, items, plugin_path)
        # Also write cartography inside the plugin itself
        write_plugin_map(
            plugin_path, ".cartographer", version, items, plugin_path,
        )

    (output_dir / "index.md").write_text(
        "\n".join(index_lines) + "\n",
        encoding="utf-8",
    )
    sys.stdout.write(
        f"Map generated: {output_dir}/ ({len(plugin_dirs)} plugins)\n",
    )


def _read_plugin_meta(plugin_path: Path) -> tuple[str, str]:
    """Read version and name from .claude-plugin/plugin.json."""
    pj = plugin_path / ".claude-plugin" / "plugin.json"
    if not pj.is_file():
        return "", ""
    try:
        meta = json.loads(pj.read_text(encoding="utf-8"))
        return meta.get("version", ""), meta.get("name", "")
    except (json.JSONDecodeError, KeyError, OSError):
        return "", ""


if __name__ == "__main__":
    main()
